### ISSUE TITLE
Invalid sbt-launch.jar file

### ISSUE THREAD

**Issue by feribg** [PredictionIO/PredictionIO#146] opened 2015-09-18 20:15 UTC
I keep getting this when trying to build from source:

```./make-distribution.sh 
Building binary distribution for PredictionIO 0.9.5-SNAPSHOT...
Attempting to fetch sbt
######################################################################## 100.0%
Launching sbt from /Users/feras/Dev/spaces/personal/PredictionIO/sbt/sbt-launch-0.13.7.jar
Error: Invalid or corrupt jarfile /Users/feras/Dev/spaces/personal/PredictionIO/sbt/sbt-launch-0.13.7.jar
```

Substituting the file to a downloaded version of sbt-launch-0.13.9 seems to work just fine. I can submit a pull request for that if you are having the same issue?

**Comment by tuxdna** [comment] 2015-09-19 18:11
I also saw same error sometime back, however now I can't reproduce it. Can you tell what sequence of commands you executed?

**Comment by feribg** [comment] 2015-09-19 20:53
Well i pretty much did 

```
git clone ...
cd ...
./make-distribution.sh
```

Maybe try a fresh clone in case you have anything cached and so on, but I tried a few times with a fresh copy and it kept failing with this same error.

**Comment by gogobebe2** [comment] 2015-09-19 23:08
"Error: Invalid or corrupt jarfile /Users/feras/Dev/spaces/personal/PredictionIO/sbt/sbt-launch-0.13.7.ja"
Maybe try cloning again?

**Comment by tuxdna** [comment] 2015-09-20 06:53
Following patch makes the issue apparent:

```diff
$ git diff
diff --git a/sbt/sbt-launch-lib.bash b/sbt/sbt-launch-lib.bash
index 09f151e..e53ed61 100644
--- a/sbt/sbt-launch-lib.bash
+++ b/sbt/sbt-launch-lib.bash
@@ -50,9 +50,9 @@ acquire_sbt_jar () {
     printf "Attempting to fetch sbt\n"
     JAR_DL=${JAR}.part
     if hash curl 2>/dev/null; then
-      (curl --progress-bar ${URL1} > ${JAR_DL} || curl --progress-bar ${URL2} > ${JAR_DL}) && mv ${JAR_DL} ${JAR}
+      (curl --verbose --progress-bar ${URL1} > ${JAR_DL} || curl --verbose --progress-bar ${URL2} > ${JAR_DL}) && mv ${JAR_DL} ${JAR}
     elif hash wget 2>/dev/null; then
-      (wget --progress=bar ${URL1} -O ${JAR_DL} || wget --progress=bar ${URL2} -O ${JAR_DL}) && mv ${JAR_DL} ${JAR}
+      (wget --verbose --progress=bar ${URL1} -O ${JAR_DL} || wget --verbose --progress=bar ${URL2} -O ${JAR_DL}) && mv ${JAR_DL} ${JAR}
     else
       printf "You do not have curl or wget installed, please install sbt manually from http://www.scala-sbt.org/\n"
       exit -1
```

The issue is replicated as below:


```
temp@matrix02:~/PredictionIO$ rm sbt/sbt-launch-0.13.7.jar 
temp@matrix02:~/PredictionIO$ ./make-distribution.sh 
Building binary distribution for PredictionIO 0.9.5-SNAPSHOT...
Attempting to fetch sbt
* Hostname was NOT found in DNS cache
*   Trying 54.164.8.248...
* Connected to typesafe.artifactoryonline.com (54.164.8.248) port 80 (#0)
> GET /typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.7/sbt-launch.jar HTTP/1.1
> User-Agent: curl/7.37.1
> Host: typesafe.artifactoryonline.com
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/html
< Date: Sun, 20 Sep 2015 06:49:29 GMT
* Server nginx is not blacklisted
< Server: nginx
< X-Node: nginx1c.prod-use1
< Content-Length: 162
< Connection: keep-alive
< 
{ [data not shown]
######################################################################## 100.0%* Connection #0 to host typesafe.artifactoryonline.com left intact

Launching sbt from /home/temp/PredictionIO/sbt/sbt-launch-0.13.7.jar
Error: Invalid or corrupt jarfile /home/temp/PredictionIO/sbt/sbt-launch-0.13.7.jar
temp@matrix02:~/PredictionIO$ 
```


Which basically means `typesafe.artifactoryonline.com` doesnt have correct sbt jar file.

**Comment by bararchy** [comment] 2015-09-30 11:08
I also have this issue.

**Comment by pferrel** [comment] 2015-10-01 20:46
A lot of people getting this error, @tuxdna ok to pull?

BTW good to see you here.

**Comment by saleemansari** [comment] 2015-10-02 10:21
@pferrel 

Yes, I the repository doesn't have sbt-launch.jar. I just moved  `~/.m2` folder somewhere else and then my patch works the build just fine. 

Its good to pull. :-)

**Comment by tuxdna** [comment] 2015-10-02 10:22
@pferrel 

Yes, I the repository doesn't have sbt-launch.jar. I just moved  `~/.m2` folder somewhere else and then my patch works the build just fine. 

Its good to pull. :-)

**Comment by tuxdna** [comment] 2015-10-19 20:00
Fixed in follwing PR, which is aready merged:

 * https://github.com/PredictionIO/PredictionIO/pull/147

I think we can close this issue.

**Closed** 2015-10-24 22:13 UTC
